import { Book } from './book';

export const BOOKS2021: Book[] = [
  { id: 1, title: 'Into The Promised Land', author:'C.T. Catling' },
  { id: 2, title: "Book of Corrections: Reflections on the National Crisis During the Japanese Invasion of Korea, 1592-1598", author:'Song-Nyong' },
  { id: 3, title: 'Everyone Dies Famous in a Small Town', author:'Bonnie-Sue Hitchcock'},
  { id: 4, title: 'The Exiles', author:'Christina Baker Kline' },
  { id: 5, title: 'The Paper Palace', author:'Miranda Cowley Heller' },
  { id: 6, title: 'The Alice Network', author:'Kate Quinn' },
  { id: 7, title: 'The Personal Librarian', author:'Marie benedict/ Vitoryia Christopher Murray' },
  { id: 8, title: 'Punching The Air', author:'IBI Zoboi & Yusef Salaam' },
  { id: 9, title: 'Call me athena', author:'Unknown' },
  { id: 10, title: 'The Ex Hex', author:'Unknown' },
  { id: 11, title: 'Concrete Rose', author:'Angie Thomas' },
  { id: 12, title: 'Ten Thousand Doors of January', author:'Alix E. Harrow' },
  { id: 13, title: 'Cloud Cuckoo Land', author:'Anthony Doerr' },
  { id: 14, title: '84, Charing Cross Road', author:'Helene Hanff' },
  { id: 15, title: 'The Places in Between', author:'Rory Stewart' },
  { id: 16, title: 'In Waves', author:'AJ Dungo' },
  { id: 17, title: 'They CAlled Us Enemy', author:'George Takei' },
  { id: 18, title: 'What Makes Love Last?', author:'John Gottman, Ph. D' },
  { id: 19, title: 'The Forty Rules of Love', author:'Elif Shafak' },
  { id: 20, title: 'One Drop', author:'Yaba Blay' },
  { id: 21, title: 'The Music Shop', author:'Rachel Joyce' },
  { id: 22, title: 'The Dictonary of Lost Words', author:'Pip Williams' },
  { id: 23, title: 'A Tale for the Time Being', author:'Ruth Ozeki' },
  { id: 24, title: 'Aperiogon', author:'Colum McCann' },
  { id: 25, title: 'Bending Adversity', author:'David Pilling' },
  { id: 26, title: 'The Color of Our Sky', author:'Amita Trasi' },
  { id: 27, title: 'Trick Mirror', author:'Jia Tolentio' },
  { id: 28, title: 'The Remains of the Day', author:'Kazuo Ishiguro' },
  { id: 29, title: 'Where the Lost Wander', author:'Amy Harmon' },
  { id: 30, title: "The Beauty of Your Face: One Woman's Life in a Nation at Odds with Its Ideals", author:'Sahar Mustafah' },
  { id: 31, title: 'The Guest Cat', author:'Takashi Hiraide' },
  { id: 32, title: 'Sweet Bean Paste', author:'Durian Sukegawa' },
  { id: 33, title: 'Lovely War', author:'Julie Berry' },
  { id: 34, title: 'Upheaval: Turning Points for Nations in Crisis', author:'Jared Diamond' },
  { id: 35, title: "A Civic Technologist's Practical Guide", author:'Cyd Harrell' },
  { id: 36, title: 'Minor Detail', author:'Adania Shibli' },
  { id: 37, title: 'Gargoyles', author:'Harriet Mercer' },
  { id: 38, title: 'Indelicacy', author:'Amina Cain' },
  { id: 39, title: 'This is Happiness', author:'Niall Williams' },
  { id: 40, title: 'Olive Kitteridge', author:'Elizabeth Strout' },
  { id: 41, title: 'The Water Dancer', author:'Ta-Nehisi Coates' },
  { id: 42, title: 'The Yellow House', author:'Sarah M. Broom' },
  { id: 43, title: 'The Nickel Boys', author:'Colson Whitehead' },
  { id: 44, title: 'The White Book', author:'Han Kang' },
  { id: 45, title: 'Mouthful of Birds', author:'Samantha Schweblin' },
  { id: 46, title: 'Open Water', author:'Caleb Azumah Nelson' },
  { id: 47, title: 'Human Acts', author:'Han Kang' },
  { id: 48, title: 'An Every Morning The Way Home Gets Longer and Longer', author:'Fredrick Backman' },
  { id: 49, title: 'Peak Performance', author:'Unknown' },
  { id: 50, title: 'The Mountain is You: Transforming Self-Sabotage Into Self-Mastery', author:'Brianna West' },
  { id: 51, title: 'The Accusation: Forbidden Stories from inside North Korea', author:'Bandi' },
  { id: 52, title: "Shut Up You're Pretty", author:'Téa Mutonji' },
  { id: 53, title: 'The Snow Child', author:'Eowyn Ivey' },
  { id: 54, title: 'The Bakeshop at Pumkin and Spice', author:'Donna Kauffman' },
  { id: 55, title: 'The imortalists', author:'Chloe Benjamin' },
  { id: 56, title: 'The Bookshop on the Corner', author:'Jenny Colgan' },
  { id: 57, title: 'White Rapids', author:'Pascal Blanchet' },
  { id: 58, title: 'The 48 Laws of Power', author:'Robert Gre' },
  { id: 59, title: 'Three Rooms', author:'Unknown' },
  { id: 60, title: 'The Lowland', author:'JHumpa Lahiri' },
  { id: 61, title: 'Munnu', author:'Malik Sajad' },
  { id: 62, title: 'Jellyfish', author:'Janice Galloway' },
  { id: 63, title: 'Girl at War', author:'Sara Novic' },
  { id: 64, title: 'Little Daughter: A Memoir of Survival in Burma and the West', author:'Zoya Phan' },
  { id: 65, title: 'A Burmese Heart', author:'Y.M.V. Han' },
  { id: 66, title: 'A Little Hope', author:'Ethan Joella' },
  { id: 67, title: 'Beasts of a Little Land', author:'Juhea Kim' },
  { id: 68, title: 'Kaffir Boy: An Autobiography', author:'Mark Mathabane' },
  { id: 69, title: 'Farewell, My Orange', author:'Kei Iwaki' },
  { id: 70, title: 'Dogs on the Trail', author:'Blair' },
  { id: 71, title: 'Wherever You Go, There You Are: Mindfulness Meditation in Everyday Life', author:'Jon Kabat-Zinn' },
  { id: 72, title: 'Steve Jobs', author:'Walter Isaacson' },
  { id: 73, title: 'Grown ups', author:'Marian Keyes' },
  { id: 74, title: 'Stress Less, Accomplish More', author:'Emily Fletcher' },
  { id: 75, title: 'The Big Leap', author:'Gay Hendricks' },
  { id: 76, title: 'Everything is Figure outable', author:'Marie Forleo' },
  { id: 77, title: 'We Should All be Millionaires', author:'Rachel Rogers' },
  { id: 78, title: 'Bamboozled by Jesus', author:'Yvonne Orji' }

];