import { Book } from './book';

export const BOOKS2021: Book[] = [
  { id: 1, read: false, title: 'Into The Promised Land', author:'C.T. Catling', library: false  },
  { id: 2, read: false, title: "Book of Corrections: Reflections on the National Crisis During the Japanese Invasion of Korea, 1592-1598", author:'Song-Nyong', library: false  },
  { id: 3, read: false, title: 'Everyone Dies Famous in a Small Town', author:'Bonnie-Sue Hitchcock', library: false },
  { id: 4, read: false, title: 'The Exiles', author:'Christina Baker Kline', library: false  },
  { id: 5, read: false, title: 'The Paper Palace', author:'Miranda Cowley Heller', library: false },
  { id: 6, read: false, title: 'The Alice Network', author:'Kate Quinn', library: false  },
  { id: 7, read: false, title: 'The Personal Librarian', author:'Marie benedict/ Vitoryia Christopher Murray', library: false  },
  { id: 8, read: false, title: 'Punching The Air', author:'IBI Zoboi & Yusef Salaam', library: false  },
  { id: 9, read: false, title: 'Call me athena', author:'Unknown', library: false  },
  { id: 10, read: false, title: 'The Ex Hex', author:'Unknown', library: false  },
  { id: 11, read: false, title: 'Concrete Rose', author:'Angie Thomas', library: false  },
  { id: 12, read: false, title: 'Ten Thousand Doors of January', author:'Alix E. Harrow', library: false  },
  { id: 13, read: false, title: 'Cloud Cuckoo Land', author:'Anthony Doerr', library: false  },
  { id: 14, read: false, title: '84, Charing Cross Road', author:'Helene Hanff', library: false  },
  { id: 15, read: false, title: 'The Places in Between', author:'Rory Stewart', library: false  },
  { id: 16, read: false, title: 'In Waves', author:'AJ Dungo', library: false  },
  { id: 17, read: false, title: 'They CAlled Us Enemy', author:'George Takei', library: false  },
  { id: 18, read: false, title: 'What Makes Love Last?', author:'John Gottman, Ph. D', library: false  },
  { id: 19, read: false, title: 'The Forty Rules of Love', author:'Elif Shafak', library: false  },
  { id: 20, read: false, title: 'One Drop', author:'Yaba Blay', library: false  },
  { id: 21, read: false, title: 'The Music Shop', author:'Rachel Joyce', library: false  },
  { id: 22, read: false, title: 'The Dictonary of Lost Words', author:'Pip Williams', library: false  },
  { id: 23, read: false, title: 'A Tale for the Time Being', author:'Ruth Ozeki', library: false  },
  { id: 24, read: false, title: 'Aperiogon', author:'Colum McCann', library: false  },
  { id: 25, read: false, title: 'Bending Adversity', author:'David Pilling', library: false  },
  { id: 26, read: false, title: 'The Color of Our Sky', author:'Amita Trasi', library: false  },
  { id: 27, read: false, title: 'Trick Mirror', author:'Jia Tolentio', library: false  },
  { id: 28, read: false, title: 'The Remains of the Day', author:'Kazuo Ishiguro', library: false  },
  { id: 29, read: false, title: 'Where the Lost Wander', author:'Amy Harmon', library: false  },
  { id: 30, read: false, title: "The Beauty of Your Face: One Woman's Life in a Nation at Odds with Its Ideals", author:'Sahar Mustafah', library: false  },
  { id: 31, read: false, title: 'The Guest Cat', author:'Takashi Hiraide', library: false },
  { id: 32, read: false, title: 'Sweet Bean Paste', author:'Durian Sukegawa', library: false  },
  { id: 33, read: false, title: 'Lovely War', author:'Julie Berry', library: false  },
  { id: 34, read: false, title: 'Upheaval: Turning Points for Nations in Crisis', author:'Jared Diamond', library: false  },
  { id: 35, read: false, title: "A Civic Technologist's Practical Guide", author:'Cyd Harrell', library: false  },
  { id: 36, read: false, title: 'Minor Detail', author:'Adania Shibli', library: false  },
  { id: 37, read: false, title: 'Gargoyles', author:'Harriet Mercer', library: false  },
  { id: 38, read: false, title: 'Indelicacy', author:'Amina Cain', library: false  },
  { id: 39, read: false, title: 'This is Happiness', author:'Niall Williams', library: false  },
  { id: 40, read: false, title: 'Olive Kitteridge', author:'Elizabeth Strout', library: false  },
  { id: 41, read: false, title: 'The Water Dancer', author:'Ta-Nehisi Coates', library: false  },
  { id: 42, read: false, title: 'The Yellow House', author:'Sarah M. Broom', library: false  },
  { id: 43, read: false, title: 'The Nickel Boys', author:'Colson Whitehead', library: false  },
  { id: 44, read: false, title: 'The White Book', author:'Han Kang', library: false  },
  { id: 45, read: false, title: 'Mouthful of Birds', author:'Samantha Schweblin', library: false  },
  { id: 46, read: false, title: 'Open Water', author:'Caleb Azumah Nelson', library: false  },
  { id: 47, read: false, title: 'Human Acts', author:'Han Kang', library: false  },
  { id: 48, read: false, title: 'An Every Morning The Way Home Gets Longer and Longer', author:'Fredrick Backman', library: false  },
  { id: 49, read: false, title: 'Peak Performance', author:'Unknown', library: false  },
  { id: 50, read: false, title: 'The Mountain is You: Transforming Self-Sabotage Into Self-Mastery', author:'Brianna West', library: false  },
  { id: 51, read: false, title: 'The Accusation: Forbidden Stories from inside North Korea', author:'Bandi', library: false  },
  { id: 52, read: false, title: "Shut Up You're Pretty", author:'Téa Mutonji', library: false  },
  { id: 53, read: false, title: 'The Snow Child', author:'Eowyn Ivey', library: false  },
  { id: 54, read: false, title: 'The Bakeshop at Pumkin and Spice', author:'Donna Kauffman', library: false  },
  { id: 55, read: false, title: 'The imortalists', author:'Chloe Benjamin', library: false  },
  { id: 56, read: false, title: 'The Bookshop on the Corner', author:'Jenny Colgan', library: false  },
  { id: 57, read: false, title: 'White Rapids', author:'Pascal Blanchet', library: false  },
  { id: 58, read: false, title: 'The 48 Laws of Power', author:'Robert Gre', library: false  },
  { id: 59, read: false, title: 'Three Rooms', author:'Unknown', library: false  },
  { id: 60, read: false, title: 'The Lowland', author:'JHumpa Lahiri', library: false  },
  { id: 61, read: false, title: 'Munnu', author:'Malik Sajad', library: false  },
  { id: 62, read: false, title: 'Jellyfish', author:'Janice Galloway', library: false  },
  { id: 63, read: false, title: 'Girl at War', author:'Sara Novic', library: false  },
  { id: 64, read: false, title: 'Little Daughter: A Memoir of Survival in Burma and the West', author:'Zoya Phan', library: false  },
  { id: 65, read: false, title: 'A Burmese Heart', author:'Y.M.V. Han', library: false  },
  { id: 66, read: false, title: 'A Little Hope', author:'Ethan Joella', library: false  },
  { id: 67, read: false, title: 'Beasts of a Little Land', author:'Juhea Kim', library: false  },
  { id: 68, read: false, title: 'Kaffir Boy: An Autobiography', author:'Mark Mathabane', library: false  },
  { id: 69, read: false, title: 'Farewell, My Orange', author:'Kei Iwaki', library: false  },
  { id: 70, read: false, title: 'Dogs on the Trail', author:'Blair', library: false  },
  { id: 71, read: false, title: 'Wherever You Go, There You Are: Mindfulness Meditation in Everyday Life', author:'Jon Kabat-Zinn', library: false  },
  { id: 72, read: false, title: 'Steve Jobs', author:'Walter Isaacson', library: false  },
  { id: 73, read: false, title: 'Grown ups', author:'Marian Keyes', library: false  },
  { id: 74, read: false, title: 'Stress Less, Accomplish More', author:'Emily Fletcher', library: false  },
  { id: 75, read: false, title: 'The Big Leap', author:'Gay Hendricks', library: false  },
  { id: 76, read: false, title: 'Everything is Figure outable', author:'Marie Forleo', library: false  },
  { id: 77, read: false, title: 'We Should All be Millionaires', author:'Rachel Rogers', library: false  },
  { id: 78, read: false, title: 'Bamboozled by Jesus', author:'Yvonne Orji', library: false  }

];